name: Publish Documentation

on: [push, pull_request]
#on:
#  push:
#    tags: 
#      - update-*

jobs:
  build:
    runs-on: ubuntu-18.04
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Checkout docs host repo
        uses: actions/checkout@v2
        with:
          repository: ezEngine/docs
          path: _site
          fetch-depth: 1
          persist-credentials: false

      - name: Clear docs host repo
        run: rm -rf _site/*

      - name: Get mono
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          sudo sh -c 'echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" > /etc/apt/sources.list.d/mono-official-stable.list'
          sudo apt-get update
          sudo apt-get install mono-complete --yes
      - name: Build docs
        run: |
          mono tools/docfx/docfx.exe
          cp CNAME _site/CNAME
      - name: Commit
        run: |
          export GIT_COMMITTER_NAME=$(git show -s --format='%cn')
          export GIT_COMMITTER_EMAIL=$(git show -s --format='%ce')
          export GIT_AUTHOR_NAME=$(git show -s --format='%an')
          export GIT_AUTHOR_EMAIL=$(git show -s --format='%ae')
          export COMMIT_HASH=$(git show -s --format='%H')
          export SUBJECT=$(git show -s --format='%s')
          cd _site
          git add .
          git commit -m "$SUBJECT" -m "Original commit: $COMMIT_HASH"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          branch: main
          directory: _site
          repository: ezEngine/docs
          force: true